# Generated by Django 4.0.1 on 2022-02-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория(ю)', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_up',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='view',
            new_name='views',
        ),
    ]
